name: CI master

on:
  # CI trigger si: push sur master / nouvelle release
  push:
    branches:
      - 'master'
  release:
    types:
      - created

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: alternbot
          POSTGRES_PASSWORD: muchsecurity
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      LOG_LEVEL: DEBUG
      DB_URL: jdbc:postgresql://localhost:5432/alternbot
      DB_USER: postgres
      DB_PASSWORD: muchsecurity
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      SERVER_TEST: ${{ secrets.SERVER_TEST }}
      CHANNEL_TEST: ${{ secrets.CHANNEL_TEST }}
      SCHEDULE_URL: ${{ secrets.SCHEDULE_URL }}

    steps:
    - name: Checkout du code
      uses: actions/checkout@v2

    - name: Setup environnement Java
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Cache packages Maven
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Compilation
      run: mvn package -DskipTests

    - name: Exécution des migrations
      run: mvn flyway:migrate

    - name: Tests unitaires
      run: mvn test

    - name: Génération badge Coverage
      id: cov-badge
      uses: cicirello/jacoco-badge-generator@v1.0.0
      with:
        jacoco-badge-file: coverage.svg

    - name: Log taux de Coverage
      run: |
        echo "Coverage: ${{ steps.cov-badge.outputs.coverage }}"

    - name: Publication badge Coverage
      uses: google-github-actions/upload-cloud-storage@main
      with:
        credentials: ${{ secrets.GCP_CREDENTIALS }}
        path: coverage.svg
        destination: alternbot-coverage/badges

    - name: Publication rapport Coverage
      uses: google-github-actions/upload-cloud-storage@main
      with:
        credentials: ${{ secrets.GCP_CREDENTIALS }}
        path: target/site/jacoco
        destination: alternbot-coverage
